default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: esg-website-development

test:
  <<: *default
  database: esg-website-test

production:
  <<: *default
  database: esg-website-production
